name = "soren-portfolio"
compatibility_date = "2024-01-01"

# Pages 配置 - 使用 @cloudflare/next-on-pages 构建输出
pages_build_output_dir = ".vercel/output/static"

# 环境变量
[vars]
NODE_ENV = "production"

# 如果需要数据库或其他服务
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"

# 自定义域名配置（部署后在Dashboard中设置）
# [env.production]
# routes = [
#   { pattern = "yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
